services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/backend
      - ../:/timon
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/frontend
    depends_on:
      - backend
#   workspace:
#    image: busybox:latest
#    volumes:
#      - ../:/timon
